-- SUPABASE SETUP SCRIPT FOR ANAIS CONTENT
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create table for Site Settings (Single row with ID 1)
CREATE TABLE IF NOT EXISTS public.site_settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    brand_name TEXT DEFAULT 'Anais Content',
    full_name TEXT DEFAULT 'Anais Cruz',
    seo_description TEXT,
    logo_url TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    instagram_url TEXT,
    linkedin_url TEXT,
    footer_tagline TEXT,
    services_bg_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert initial row if not exists
INSERT INTO public.site_settings (id, brand_name, full_name)
VALUES (1, 'Anais Content', 'Anais Cruz')
ON CONFLICT (id) DO NOTHING;

-- 2. Create table for Hero section
CREATE TABLE IF NOT EXISTS public.hero (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT DEFAULT 'Anais Cruz',
    subtitle TEXT,
    cta_text TEXT DEFAULT 'Ver Mi Trabajo',
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.hero (id, title)
VALUES (1, 'Anais Cruz')
ON CONFLICT (id) DO NOTHING;

-- 3. Create table for About section
CREATE TABLE IF NOT EXISTS public.about (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    main_title TEXT,
    description TEXT,
    experience TEXT,
    gallery JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.about (id, main_title)
VALUES (1, 'Estrategia & narrativa visual')
ON CONFLICT (id) DO NOTHING;

-- 4. Create table for Services
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    icon TEXT,
    title TEXT NOT NULL,
    subtitle TEXT,
    description TEXT,
    tag TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create table for Portfolio
CREATE TABLE IF NOT EXISTS public.portfolio (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    category TEXT,
    location TEXT,
    image_url TEXT,
    gallery JSONB DEFAULT '[]'::jsonb,
    is_wide BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Create table for Partners/Clients
CREATE TABLE IF NOT EXISTS public.partners (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    logo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Create table for Testimonials
CREATE TABLE IF NOT EXISTS public.testimonials (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    role TEXT,
    content TEXT NOT NULL,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Create table for Contact Messages
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    email TEXT,
    message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Create table for Analytics (Simplified)
CREATE TABLE IF NOT EXISTS public.analytics (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id TEXT,
    page_path TEXT,
    visitor_info JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Create table for Admin Access
CREATE TABLE IF NOT EXISTS public.admin_access (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT DEFAULT 'admin',
    password TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.admin_access (id, username, password)
VALUES (1, 'admin', 'admin123')
ON CONFLICT (id) DO NOTHING;

-- 11. Storage Setup
-- Note: You need to create a bucket named 'assets' manually in the Supabase Dashboard
-- and set it to PUBLIC access.

-- RLS POLICIES (Simple version: Everyone can read, Only authenticated/with secret can write)
-- For a landing page, we usually keep read public.

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hero ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.about ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_access ENABLE ROW LEVEL SECURITY;

-- Allow public read access to everything except messages, analytics and admin_access
CREATE POLICY "Public Read Site Settings" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "Public Read Hero" ON public.hero FOR SELECT USING (true);
CREATE POLICY "Public Read About" ON public.about FOR SELECT USING (true);
CREATE POLICY "Public Read Services" ON public.services FOR SELECT USING (true);
CREATE POLICY "Public Read Portfolio" ON public.portfolio FOR SELECT USING (true);
CREATE POLICY "Public Read Partners" ON public.partners FOR SELECT USING (true);
CREATE POLICY "Public Read Testimonials" ON public.testimonials FOR SELECT USING (true);
CREATE POLICY "Public Read Admin Access" ON public.admin_access FOR SELECT USING (true);

-- Allow public insert to messages (Contact Form) and analytics
CREATE POLICY "Public Insert Messages" ON public.messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Insert Analytics" ON public.analytics FOR INSERT WITH CHECK (true);

-- Admin policies (For development simplicity, we assume the admin uses the API directly or you configure Auth)
-- For now, if you want the Admin Panel to work without complex Auth setup:
CREATE POLICY "Full Access Admin Site Settings" ON public.site_settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full Access Admin Hero" ON public.hero FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full Access Admin About" ON public.about FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full Access Admin Services" ON public.services FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full Access Admin Portfolio" ON public.portfolio FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full Access Admin Partners" ON public.partners FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full Access Admin Testimonials" ON public.testimonials FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full Access Admin Messages" ON public.messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full Access Admin Analytics" ON public.analytics FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Full Access Admin Access" ON public.admin_access FOR ALL USING (true) WITH CHECK (true);
